services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    working_dir: /app
    command: npm run start
    environment:
      - PORT=4000
      - NODE_ENV=production
      - CLOUD=aws
      - SSM_PARAMETER_PATH=/your/env/path/
      - AWS_BUCKET=rez541bucket
    networks:
      - nsvenet
  frontend:
    build: ./frontend
    container_name: frontend_service
    networks:
      - nsvenet
  web:
    image: nginx:alpine
    container_name: web_service
    ports:
      - "8080:80"
    volumes:
      # Mount the NGINX configuration file
      - ./web/prod/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/html:/usr/share/nginx/html
      - ./web/prod/logs:/var/log/nginx
    networks:
      - nsvenet
    depends_on:
      - backend
      - frontend
networks:
  nsvenet:
    driver: bridge
    
    